### ISSUE TITLE
Cycle Text Feedback

### ISSUE THREAD

**Issue by harshkhandeparkar** [proffapt/fERP#17]
Add a feature to cycle between different text feedbacks (strengths and weaknesses) while keeping the rest of the inputs the same.

**Comment by proffapt** [comment]
Thanks for taking up on improving the extension.
Will be looking up for you to implement it before the deadline to fill forms :)

**Comment by proffapt** [comment]
I don't think that's a viable feature to be added. I can't see any use of it since the ideology is like use the extension once (2 clicks) and no need to return to extension window.. the form will be filled automatically, this feature will be like unwanted child which will just take efforts for no reason..

**Comment by harshkhandeparkar** [comment]
> I don't think that's a viable feature to be added. I can't see any use of it since the ideology is like use the extension once (2 clicks) and no need to return to extension window.. the form will be filled automatically, this feature will be like unwanted child which will just take efforts for no reason..

That's a good business decision.
