### ISSUE TITLE
Auto-filling recaptcha, submitting the feedback and providing same feedback to all courses should be disabled by default

### ISSUE THREAD

**Issue by sibashis12** [proffapt/fERP#43]
I wanted fERP to fill in the details and then stop. I wanted to make some edits regarding the feedback I wanted to submit and had actual criticism to give regarding things. But auto-submit was on by default and before I realised it, fERP had already submitted feedback to the courses where I wanted to criticise some of the practises of the professors and the course itself. I wanted to give negative feedback to a particular prof but fERP gave positive to him.

Auto-filling recaptcha, giving same feedback to all courses should be disabled by default.

A dialog box asking if we want auto-filling recaptcha and giving same feedback should be provided before it starts submitting the feedback because at the press of the type of feedback, it blasts through all the courses not giving the user time to figure out what is happening.

None.

**Comment by proffapt** [comment]
Earlier, they were disabled by default. Later, I realized exactly what you did: people don't actually bother seeing the UI of whatever they are using. The UI for fERP is minimal, with three buttons and 2 checkboxes. Just like you never saw that they existed and continued earlier, people would never look at them and fill every course one by one.

> A dialog box asking if we want auto-filling recaptcha and giving the same feedback should be provided before it starts submitting the feedback

Literally, 2 lines are there before someone presses the button `¯\_(ツ)_/¯`

<img width="261" alt="image" src="https://github.com/user-attachments/assets/e9d2a10e-2045-44bf-b64b-df3813472328">

Even if the lines aren't clear, there are tooltips to explain what that option does.

Creating this auto-filler, which navigates from course to prof automatically, was a nightmare, and listening to people saying, "Wow, was it even there?" is a loss to me - a loss to the time I spent developing it before endsems. That's why these options are enabled by default.

If I disable any of them by default, no one would bother looking at them. And, they would come to me saying if 'captcha filler' or 'course navigator' was there, it would have been perfect - yup, I have received these reviews.

So, I would recommend you take a look next time you fill out the feedback form. Not closing the issue till your response; if this answers your query, then you are encouraged to self-close the issue. Thanks.

**Comment by sibashis12** [comment]
You are right. I should have read the features of the extension before using it. I agree that there are a lot of people who do not care much about the feedback form. There are a lot of issues with the feedback form which is why it takes so damn long to complete it. But still, if possible, kindly make a minor modification in UI maybe so that the two checkboxes are slightly bigger in size and/or appear before the feedback type options so people who genuinely have feedback they want to give in some courses are not robbed of that opportunity. You could also add a generate feedback button so that people can make the positive/neutral/negative feedback choice, then look at the two checkboxes and then click the generate feedback button. I certainly did not expect the process to start as soon as I selected the feedback type. I agree that there is more fault on my part though so I closed the issue.
